### ISSUE TITLE
Should verify fields when users update me

### ISSUE THREAD

**Issue by suminhthanh** [minhuyen/generator-expressjs-rest#83]
https://github.com/minhuyen/generator-expressjs-rest/blob/cc8c161ce36199048e5f22963b6aad462a09f247/generators/app/templates/backend/src/api/users/index.js#L60

I think we should verify fields when user use `update me` function to avoid them updating themselves from the role from `user` to `admin` or something like that they want.

**Comment by minhuyen** [comment]
Greate! You are right.

Thanks for your feedback.

Can you make a pr to fix it?

Thanks

**Comment by minhuyen** [comment]
@suminhthanh Thanks for your contribution.

**Comment by suminhthanh** [comment]
You're welcome. I’m glad to work with you
